grpc:
  server:
    port: 9000
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products
      username: root
      password: example
      authentication-database: admin
